Travis: build using Xenial 16.04 instead of Trusty 14.04 to fix build
At one point, Travis started failing while trying to link vcpkg with:

hash.cpp:(.text+0xb9d9): undefined reference to `std::iostream_category()'

It seems something broke along the way with gcc-8 toolchain on Trusty,
and as per https://github.com/microsoft/vcpkg/issues/8066, I've decided
to just upgrade to use Xenial, which works fine.